name: Deploy

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/metro-hermes-compiler/**"
      - ".github/workflows/build-emhermesc.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Clone hermes
        run: git clone https://github.com/facebook/hermes

      - name: Build host hermes
        uses: seanmiddleditch/gha-setup-ninja@master
        run: python3 ./hermes/utils/build/configure.py ./build_host_hermes

      - name: Build emhermesc.js
        uses: mymindstorm/setup-emsdk@v11
        run: |
          python3 ./hermes/utils/build/configure.py \
            --cmake-flags " -DIMPORT_HERMESC:PATH=./build_host_hermesc/ImportHermesc.cmake " \
            --distribute \
            --wasm \
            --emscripten-platform=upstream \
            --emscripten-root="$EMSDK" \
            ./embuild