name: Deploy

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/metro-hermes-compiler/**"
      - ".github/workflows/build-emhermesc.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Clone hermes
        run: git clone https://github.com/facebook/hermes

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Debug
        run: which ninja

      - name: Debug path
        run: echo $PATH

      - name: Debug build_host_hermes
        run: find ./build_host_hermes

      - name: Build host hermes
        run: python3 ./hermes/utils/build/configure.py ./build_host_hermes

      - name: Setup EMSDK
        uses: mymindstorm/setup-emsdk@v11

      - name: Build emhermesc.js
        run: |
          python3 ./hermes/utils/build/configure.py \
            --cmake-flags " -DIMPORT_HERMESC:PATH=`pwd`/build_host_hermesc/ImportHermesc.cmake " \
            --distribute \
            --wasm \
            --emscripten-platform=upstream \
            --emscripten-root="$EMSDK/upstream/emscripten" \
            `pwd`/embuild