name: Deploy

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/metro-hermes-compiler/**"
      - ".github/workflows/build-emhermesc.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Clone hermes
        run: git clone https://github.com/facebook/hermes $RUNNER_TEMP/hermes

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure host hermes
        run: python3 $RUNNER_TEMP/hermes/utils/build/configure.py $RUNNER_TEMP/build_host_hermes
      
      - name: Build host hermes
        run: cmake --build $RUNNER_TEMP/build_host_hermes --target hermesc

      - name: Setup EMSDK
        uses: mymindstorm/setup-emsdk@v11

      - name: Configure Emscripten build
        run: |
          python3 $RUNNER_TEMP/hermes/utils/build/configure.py \
            --cmake-flags " -DIMPORT_HERMESC:PATH=$RUNNER_TEMP/build_host_hermes/ImportHermesc.cmake " \
            --distribute \
            --wasm \
            --emscripten-platform=upstream \
            --emscripten-root="$EMSDK/upstream/emscripten" \
            $RUNNER_TEMP/embuild

      - name: Build
        run: cmake --build $RUNNER_TEMP/embuild --target hermes

      - name: Show result
        run: ls -la $RUNNER_TEMP/embuild/bin

      - name: Move build output
        run: mv $RUNNER_TEMP/embuild/bin ./output

      - name: Show output
        run: ls -la output

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: emhermesc.js
          path: output/hermes.js

      - name: Upload build artifact (WASM)
        uses: actions/upload-artifact@v3
        with:
          name: emhermesc.wasm
          path: output/hermes.wasm