name: Deploy

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/metro-hermes-compiler/**"
      - ".github/workflows/build-emhermesc.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Clone hermes
        run: git clone https://github.com/facebook/hermes

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build host hermes
        run: python3 $GITHUB_WORKSPACE/hermes/utils/build/configure.py $GITHUB_WORKSPACE/build_host_hermes

      - name: Setup EMSDK
        uses: mymindstorm/setup-emsdk@v11

      - name: Build emhermesc.js
        run: |
          python3 ./hermes/utils/build/configure.py \
            --cmake-flags " -DIMPORT_HERMESC:PATH=$GITHUB_WORKSPACE/build_host_hermes/ImportHermesc.cmake " \
            --distribute \
            --wasm \
            --emscripten-platform=upstream \
            --emscripten-root="$EMSDK/upstream/emscripten" \
            $GITHUB_WORKSPACE/embuild

      - name: Show result
        run: ls -la $GITHUB_WORKSPACE/embuild